- hosts: web1
  become: yes
  become_method: sudo
  roles:
    - mariadb
    - nginx
- name: set firewall
  hosts: web1
  vars:
    http_port: 80

    task:
    - firewalld:
      service: '{{ http_port }}'
      permanent: true
      state: enabled
